#!/bin/sh
# Generate anylmdb_rename<stream>.h: #define lines that prefix every extern
# symbol of one vendored LMDB stream so both streams can be linked into one
# library. Run by update-lmdb.sh; the output is checked in, so consumers
# never need this script.
#
# The list is derived from `nm` on objects compiled WITHOUT renames (headers
# alone are not enough: e.g. 0.9's midl.c defines mdb_midl_insert which its
# midl.h does not declare), plus a grep of the pristine headers for names
# that are declared but not compiled here (mdb_modload/modunload/modsetup
# live in 1.0's module.c, which anylmdb does not build).

set -eu

stream=${1:?usage: gen-rename.sh <09|10>}
case "$stream" in
09) snum=9 ;;
10) snum=10 ;;
*) echo "error: stream must be 09 or 10" >&2; exit 1 ;;
esac

cd "$(dirname "$0")/.."
root=$(pwd)
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# Compile both engine TUs without any renaming.
cat > "$tmp/mdb.c" <<EOF
#define ANYLMDB_STREAM $snum
#include "mdb_lmdb${stream}.c.h"
EOF
cat > "$tmp/midl.c" <<EOF
#define ANYLMDB_STREAM $snum
#include "midl_lmdb${stream}.c.h"
EOF

: "${CC:=cc}"
syms="$tmp/syms"
for extra in "" "-DMDB_RPAGE_CACHE=1"; do
    # The extra MDB_RPAGE_CACHE pass captures mdb_mid3l_* on stream 10;
    # harmless duplicate work on stream 09.
    $CC -c -O0 -pthread -I"$root" $extra -o "$tmp/mdb.o" "$tmp/mdb.c"
    $CC -c -O0 -pthread -I"$root" $extra -o "$tmp/midl.o" "$tmp/midl.c"
    # POSIX output format; strip the Mach-O leading underscore.
    nm -gP "$tmp/mdb.o" "$tmp/midl.o" \
        | awk '$2 != "U" && $2 != "" && $1 != "" {print $1}' \
        | sed -e 's/^_//' -e '/^$/d' >> "$syms"
done

# Extern symbols that exist only in _WIN32 builds of the engines: nm on the
# POSIX-built objects above cannot see them. mdb_tls_cbp is the TLS-callback
# anchor both engines place in .CRT$XLB (see mdb_tls_callback in mdb.c).
printf 'mdb_tls_cbp\n' >> "$syms"

sort -u "$syms" > "$syms.nm"

# Names declared in the pristine headers (may include declared-but-not-
# compiled functions like 1.0's mdb_modload/modunload/modsetup; renaming a
# never-defined declaration is harmless). Names that are only compat macros
# in the headers (0.9's mdb_open/mdb_close) must NOT be renamed: an
# object-like rename macro would clash with their function-like definition.
# The nm set stays authoritative either way (e.g. mdb_env_create is
# macro-defined under MDB_VL32, which we do not build).
grep -ohE '\bmdb_[a-z0-9_]+[[:space:]]*\(' \
        "lmdb_lmdb${stream}.h" "midl_lmdb${stream}.h" \
    | sed -E 's/[[:space:]]*\($//' | sort -u > "$syms.hdr"
grep -hE '^[[:space:]]*#[[:space:]]*define[[:space:]]+mdb_[a-z0-9_]+\(' \
        "lmdb_lmdb${stream}.h" "midl_lmdb${stream}.h" \
    | sed -E 's/^[[:space:]]*#[[:space:]]*define[[:space:]]+(mdb_[a-z0-9_]+)\(.*/\1/' \
    | sort -u > "$syms.macros"
comm -23 "$syms.hdr" "$syms.macros" | cat - "$syms.nm" | sort -u > "$syms.uniq"

# Every extern symbol in liblmdb must be mdb_-prefixed; anything else would
# escape the rename and clash between streams.
bad=$(grep -v '^mdb_[a-z0-9_]*$' "$syms.uniq" || true)
if [ -n "$bad" ]; then
    echo "error: unexpected extern symbols in stream $stream:" >&2
    echo "$bad" >&2
    exit 1
fi

out="anylmdb_rename${stream}.h"
version=$(grep "^$stream " VERSIONS 2>/dev/null | awk '{print $2}' || true)
{
    echo "/* GENERATED by scripts/gen-rename.sh for LMDB stream $stream${version:+ (LMDB $version)}."
    echo " * Renames every extern symbol of the vendored engine so both streams"
    echo " * can live in one library. Do not edit by hand. */"
    echo "#ifndef ANYLMDB_RENAME${stream}_H"
    echo "#define ANYLMDB_RENAME${stream}_H"
    sed -E "s/^mdb_(.*)\$/#define mdb_\1 mdb${stream}_\1/" "$syms.uniq"
    echo "#endif"
} > "$out"

count=$(grep -c '^#define' "$out")
echo "$out: $count symbols renamed"
